### ISSUE TITLE
Couldn't load plugin openlayers_plugin due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by EmadElden** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#437]
ImportError: cannot import name QtWebKit 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/emadeldin/.qgis2/python/plugins/openlayers_plugin/__init__.py", line 25, in classFactory
    from openlayers_plugin import OpenlayersPlugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emadeldin/.qgis2/python/plugins/openlayers_plugin/openlayers_plugin.py", line 30, in 
    from openlayers_overview import OLOverview
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emadeldin/.qgis2/python/plugins/openlayers_plugin/openlayers_overview.py", line 23, in 
    from openlayers_ovwidget import OpenLayersOverviewWidget
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emadeldin/.qgis2/python/plugins/openlayers_plugin/openlayers_ovwidget.py", line 38, in 
    from ui_openlayers_ovwidget import Ui_Form
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emadeldin/.qgis2/python/plugins/openlayers_plugin/ui_openlayers_ovwidget.py", line 80, in 
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit

Python version: 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118] 
QGIS version: 2.14.14-Essen Essen, exported 

Python Path:
/usr/share/qgis/python
/home/emadeldin/.qgis2/python
/home/emadeldin/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/emadeldin/.qgis2//python

**Comment by DelazJ** [comment]
@EmadElden This repository is actually dedicated to issues you encounter while browsing the main website of QGIS project.

If you have issue with the application, please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html) or report in the Desktop application bug tracker as stated in the [bug report page](http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues)).
However, given your report I think your issue has to do with your OS platform (I read that QtWebkit was removed on some or something like that -- can't say more) and obviously an issue to report to the OpenLayers plugin bug tracker and not QGIS's.

Regards...
